# Site settings
title: Rajkumar Katta
description: |
  Rajkumar Katta is a NYC-based Data Scientist and a recent graduate from Metis Data Science bootcamp.
  He's interested in solving complex problems using data driven techniques.

url: https://rkatta.github.io

about_title: About
projects_title: Home

# User settings
user_description_short: |

  I'm a NYC-based data scientist. I recently graduated from Metis, a 12-week ACCET accredited data science bootcamp.

user_description_appendix: |
  
  I built this site in [Jekyll][jekyll], and it's hosted for free on [GitHub Pages][gh-pages]. It's open source, so if
  you like it, feel free to fork it on [GitHub][github] and make your own version.

  [github]: https://github.com/rkatta/rkatta.github.io
  [gh-pages]: https://pages.github.com/
  [jekyll]: https://jekyllrb.com


email: kattarajkumar@gmail.com
linkedin: r-katta
github: rkatta

relevant_tags: ['projects', 'music', 'tech-blog']

resume_url:
music_resume_url:

author: Rajkumar Katta
author_title: Data Scientist
author_photo: profile-photo.jpg
user_description_short: |
  I'm a NYC-based data scientist. I recently graduated from Metis, a 12-week ACCET accredited data science bootcamp.

## Disqus
#disqus_identifier: rassaby

## Tracker
#google_analytics_id: UA-109461282-1

#keywords: 'software,engineer,design,scala,cello,music,louis rassaby,rassaby'

## URLs
permalink: ':title/'

baseurl: 'rkatta.github.io'
projects_url: '/'
about_url: '/about'


plugins:
  - jekyll-feed


include: [_pages]
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'gulpfile.js', 'README.md']
